### PR TITLE
Re-organizing file structure and made install script

### PR DESCRIPTION
**Pull request by l0g1x**
removed meshes, added them as downloadable tar.zip to chicagoedt wiki, made install script like in igvc repo

### CODE REVIEW

**Comment by bsubei** [comment]
does this compile on Jenkins yet?

**Comment by l0g1x** [comment]
please build

**Comment by bsubei** [comment]
hahaha I love Jenkins <3

**Comment by chicagoedt** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://jenkins.chicagoedt.org/job/Software_RMC_Upstream/6/
Test PASSed.

**Pull request merged**
