### PR TITLE
teensy arduino node

### PR DESCRIPTION
**Pull request by bsubei**
teensy node runs on the teensy (uploaded using Arduino IDE and using ros_lib library).

Rotates servo and broadcasts tf based on its position.

Don't merge this yet, I still need to make it subscribe to a topic and use that to determine what direction to turn.

### CODE REVIEW

**Comment by l0g1x** [comment]
Looks like youve earned your way to tennesse so far.. ;)

Krystian Gebis
University of Illinois at Chicago

**Comment by bsubei** [comment]
@l0g1x should be coming into Georgia by now ;)

**Comment by bsubei** [comment]
more to come, fixing some bugs and adding some features

**Comment by bsubei** [comment]
mostly done. Will fix timing issue (delay before sweeping) later

**Pull request merged**
